# Working with Numpy -- for Mathematics Operations

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [7]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [23]:
# Creating Zeroes,Ones & Custom array

a = np.zeros((3,3))
print(a)

## By Default the datatypes is Float , we can change it as well
b = np.ones((2,3),dtype=np.int64)
print(b)

c = np.full((3,2),6)
print(c)

## Identity Matrix -- Size/Square Matrix
d = np.eye(4)
print(d)

## Random Matrix

randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[6 6]
 [6 6]
 [6 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.61903234 0.34302216 0.52415592]
 [0.6299625  0.33173069 0.23320393]]


In [21]:
print(randomMatrix[ : ,1])

[0.85227321 0.65769539]


In [22]:
randomMatrix[1, : ] = 1
print(randomMatrix)

[[0.15456697 0.85227321 0.33624007]
 [1.         1.         1.        ]]


In [5]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


## Numpy Random Module

In [7]:
np.random.shuffle(a)
print(a)

[14  5 12 11 10  7  8  9 13  6]


In [14]:
# Returns values from a Standard Distribution Function
a = np.random.randn(4,5)
print(a)

b = np.random.randint(5,10,4)
print(b)

## Randomly Picks one Element from an array
c = np.random.choice([12,4,5,44,6,6,7,8,89,9,0,0,76,5,4,3,3,23,5,67,8,9,9,6,5,90,4])
print(c)

[[-0.71830851 -0.5656437   0.82908342  0.10743895  0.53262988]
 [-1.64561283  0.27861105 -1.0234097  -1.27377664  0.1660144 ]
 [-0.37290829  0.93456738  1.08907213  0.89197329 -0.51000115]
 [ 0.70397343  1.03343506  0.61790235 -0.42238222  0.54191754]]
[9 6 9 9]
5


# Numpy Statistics Function

In [15]:
a = np.array([[1,2,3,5],[7,9,19,12]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[ 1  2  3  5]
 [ 7  9 19 12]]
1
[1 2 3 5]
[1 7]


In [22]:
# Mean
b = np.array([1,3,4,6,7,8])
print(b)
m = sum(b)/6
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[1 3 4 6 7 8]
4.833333333333333
4.833333333333333
[ 4.   5.5 11.   8.5]
[ 2.75 11.75]


In [24]:
# Median
c = np.median(b)
print(c)

5.0


In [33]:
# Weights
f = np.array([1,2,0,45,7])
w = np.array([1,1,1,1,1])
print(np.average(f,weights=w))

# Standard Deviation
u = m=np.mean(f)
myStd = np.sqrt(np.mean(abs(f-u)**2))
print(myStd)

# Inbuilt-Functions
dev = np.std(f)
print(dev)

# Variance
print(myStd**2)
print(np.var(f))

11.0
17.1697408250678
17.1697408250678
294.79999999999995
294.8
